# Example for programconfig.yaml
# copy to programconfig.yaml to set the parameters
# programconfig_template.yaml will be overwritten by the next update
retryDelaysForBasic: 5 10 20 40 60 60 60 60 60 60 60 60 60 60

# Delete old events once per day
startDeleteOldEvents: 1
deleteOldEventsHour: 10
deleteOldEventsMinutes: 2
deleteOldEventsDaysToKeep: 180
deleteOldEventsMaxDaysToDelete: 10

# Workaround for Buttons: space separated list of nodes needing the workaround
workaroundForButtons:

# where to send the device event
udpIpAddress: 127.0.0.1

# do not request battery value if the devices wakes up too often
minBatteryIntervall: 0
